@scheme = http
@host = localhost
@port = 3002

#@scheme = https
#@host = api-bsv.satocash.com
#@port = 443


GET {{scheme}}://{{host}}:{{port}}/api/blocks/593500

GET {{scheme}}://{{host}}:{{port}}/api/blocks/593500/transactions?offset=0&limit=50

GET {{scheme}}://{{host}}:{{port}}/api/blocks/593500/transactions?offset=50&limit=50

GET {{scheme}}://{{host}}:{{port}}/api/blocks/593500/transactions?limit=100

GET {{scheme}}://{{host}}:{{port}}/api/blocks/593500/transactions?offset=1&limit=100

GET {{scheme}}://{{host}}:{{port}}/api/transactions/53997ba8aef6200908bb54d3ed5690966096bd0c6c3cb16f479900b3d81697dc

GET {{scheme}}://{{host}}:{{port}}/api/blocks/593540